### ISSUE TITLE
Could you add a more detailed example code?

### ISSUE THREAD

**Issue by joaromi** [jurihock/sdft#1]
Hello, I am very interested in testing out this implementation for real time frequency analysis of a signal. However, I do not understand how to implement the method.

In scipy.ftt I would compute a sliding window with the last 'n' values and perform the fourier transform on the array. Using sdft I would be able to update the transform online with just the last value and the result of the previous iteration right? 

Could you upload a basic example with a couple of sine waves, please? Sorry for the inconvenience.

**Comment by jurihock** [comment]
The idea behind the SDFT is actually quite simple: Put consecutive time domain samples in and get DFT vector estimate for the each of them out.

Here is just a basic analysis workflow based on the Python sketch from the readme file:

```python
import numpy as np
import matplotlib.pyplot as plot

from sdft import SDFT

# generate samples

n = 44100
m = 1000

sr = 44100
f = 5000
t = np.arange(n) / sr

x = np.sin(2 * np.pi * f * t)

# compute dft matrix

sdft = SDFT(m)

dft = sdft.sdft(x)

assert dft.shape == (n, m)

# plot spectrogram

with np.errstate(divide='ignore', invalid='ignore'):
    db = 20 * np.log10(np.abs(dft))

roi = (0, n / sr, 0, sr / 2)
args = dict(aspect='auto', cmap='inferno', interpolation='nearest', origin='lower')

plot.imshow(db.T, extent=roi, **args)
cbar = plot.colorbar()

plot.xlabel('s')
plot.ylabel('Hz')
cbar.set_label('dB')

plot.ylim(0, 10000)
plot.clim(-120, 0)

plot.show()
```

**Comment by jurihock** [comment]
See also ` examples/analysis.py`

**Comment by joaromi** [comment]
Thank you very much!
