### ISSUE TITLE
Docs: Explain Interpretation of Vector and Linear Spacing more

### ISSUE THREAD

**Issue by stellarpower** [jurihock/sdft#10]
Hi,

Nice library! Am looking forward to seeing how it performs on my data.

From the readme:
> It takes real valued samples and estimates the corresponding half size complex valued DFT vector for each of them. 

Would you be able to add a short sentence in the readme, and maybe something in the examples, that clarifies how this vector is to be interpreted please? Most of these seem to be taking the entire signal and transforming, then doing the inverse and verifying the difference isn't too great.

For my usecase though, I need to compute the bandpowers at known frequencies realtime, adding one sample at a time (and I also think an example closer to this might be helpful - e.g. plotting the phase and amplitude). So it's not entirely clear to me how the mapping between the DFT vector/bin counts and the relative frequencies is defined, whilst I have some guesses.

I would have assumed they might be linearly-spaced, for the specified number of bins, between zero and some maximum, but then if not user-specified, inferring what this upper limit is remains a question. Or does it simply count up from zero one at a time, same as the FFT - so that a total of 128 samples and a bin count of 65 would be an equivalent output format? Does the interpretation depend on how many samples I push into the algorithm, or is it fixed? Would be good if this could be confirmed somewhere in the documentation.

Thanks!

**Comment by jurihock** [comment]
Done.

**Comment by stellarpower** [comment]
Thanks!!

**Comment by stellarpower** [comment]
I am currently expanding the examples a bit more towards my usecase as I work out what I need to do - I'm more than happy to upload to a branch if you wanted to cherry-pick anything out of them. This is just in Python right now as I need to call in from some other code, but I will eventually be using the library in C++ so I may have also have some code there.

I wouldn't open a PR directly as the code style is different and I may have changed things you don't want to reflect across, but let me know if you'd like to parouse them at all and I can sanitise and upload a squashed commit at some point.

**Comment by jurihock** [comment]
The analysis examples are intended to be as simple, straightforward and identical as possible. I also use them to quickly check each SDFT implementation.

Btw, I also have the same kind of analysis examples in the log scaled [QDFT](https://github.com/jurihock/qdft). Therefore, they have to be identical in both repos for reasons of efficiency.

So if you have a specific use case for the SDFT, why not to create a new repo on GitHub and present your project there?

**Comment by stellarpower** [comment]
Well, a simple example is what I have been aiming for; I only need to extract the amplitide of some bins at given frequencies, and whilst the plotting etc. is nice, it's taken a bit of time going through the examples here and in the QDFT to reverse-engineer what is happening. But fair enough, just an offer.
