### ISSUE TITLE
Discussions Tab?

### ISSUE THREAD

**Issue by stellarpower** [jurihock/sdft#11]
Hi,

I had a question - but not a bug or FR, just wanted to be sure I had understood and was using the library properly.

I can ask here, but rather than clutter the issue list with a non-issue, would you be open to enabling the "discussions" feature in GitHub ([docs]( https://docs.github.com/en/discussions/quickstart ))?

Thanks

**Comment by jurihock** [comment]
The "discussions" are now enabled. Feel free to ask your questions related to **this** project there.
